### ISSUE TITLE
Is this dataset profile-able?

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/dravlex#3]

**Comment by tresoldi** [comment]
It surely is, and looks relatively easy. I would just wander if the duplicates are indeed geminates, as it looks, but it certainly doable.

**Comment by tresoldi** [comment]
Looks doable, especially if we can blindly trust the transcriptions and don't meddle with allophones: https://en.wikipedia.org/wiki/Tamil_phonology

**Comment by tresoldi** [comment]
The only real issue is that some lexemes should be corrected first (like `koʋʋu (noun)`), including using first form only (such as in `kaɖi ~ kajɾi`). I'll do it also to check how long it takes me.

**Comment by tresoldi** [comment]
Oh, I though it was already at pylexibank 2.1. Do you prefer me to take a look later, @SimonGreenhill ?

**Comment by SimonGreenhill** [comment]
Ah, the 2.1 is in [this PR](https://github.com/lexibank/dravlex/pull/2). If someone checks it, I'll merge and then it's all yours :)

**Comment by tresoldi** [comment]
Ah, great, was not getting notifications for that. I'll wait, once merged I'll go ahead.

**Comment by LinguList** [comment]
Hey, before doing anything, please wait, with respect to the profile.

**Comment by LinguList** [comment]
The story is: I made a profile for Annemarie back then, and it is published along with a very easy-to-handle lingpy wordlist file, that we used. So no need to work on a profile here. Just important to make sure to download the right data.

**Comment by tresoldi** [comment]
I was waiting for the merge, but if you already have one even better.

**Comment by LinguList** [comment]
[2018_02_22_lingpy_analyses_for_RSOS_SI.zip](https://github.com/lexibank/dravlex/files/3902434/2018_02_22_lingpy_analyses_for_RSOS_SI.zip)

**Comment by LinguList** [comment]
Unfortunately, these data were apparently not shipped withthe paper, but they are mentioned. So they should be placed in raw here, and I would even say: no need to get the data from the cldf into cldf, it is probably easier to just take it from there, as it also contains the raw-raw data as they prepared it?

**Comment by SimonGreenhill** [comment]
Ok, I've added the profile from your file, @LinguList -- was the tsv file updated too, or shall I keep the version from Zenodo?

**Comment by SimonGreenhill** [comment]
Only one error: 

```
Kurukh-38_hand-1 | Kurukh | 38_hand | kʰekkʰa | kʰ e kː  <<ʰ>>  a
```

**Comment by tresoldi** [comment]
@SimonGreenhill I've finished the profile (added the missing grapheme and fixed a couple of things) but I don't have writing permission. Could you add me?

**Comment by SimonGreenhill** [comment]
that's odd? how about now?

**Comment by tresoldi** [comment]
Working! I guess it was transferred into the organization and I don't get automatic writing rights?

**Comment by SimonGreenhill** [comment]
That must be it. Very strange :/
